# Generated by Django 4.1.3 on 2022-11-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='admin_passwrod',
            new_name='admin_password',
        ),
    ]
