# Generated by Django 4.1.3 on 2022-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_image',
            field=models.ImageField(default='', upload_to='department/'),
        ),
    ]
