# Generated by Django 4.1.3 on 2022-11-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0004_department_department_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_email', models.CharField(max_length=50)),
                ('doctor_password', models.CharField(max_length=30)),
                ('doctor_contact_no', models.CharField(max_length=30)),
                ('doctor_qualification', models.CharField(max_length=30)),
                ('doctor_experience', models.IntegerField()),
                ('consultation_fees', models.CharField(max_length=10)),
                ('doctor_profile_picture', models.ImageField(upload_to='doctor/')),
                ('doctor_department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_admin.department')),
            ],
        ),
    ]
