# Generated by Django 4.1.3 on 2022-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_email', models.CharField(max_length=30)),
                ('student_dob', models.CharField(max_length=20)),
                ('student_phone_number', models.BigIntegerField()),
                ('student_place', models.CharField(max_length=30)),
                ('s_parent_name', models.CharField(max_length=30)),
                ('student_profile_picture', models.ImageField(upload_to='student/')),
                ('student_password', models.CharField(max_length=20)),
            ],
        ),
    ]
